#!/bin/sh
#
# Deploys the Jekyll site directly from the Raspberry Pi to /var/www/htdocs.

JEKYLL_DEST=/var/www/html

echo "Building Jekyll site to ${JEKYLL_DEST}..."
jekyll build -d $JEKYLL_DEST

# Test if jekyll build was succesfull
RESULT_JEKYLL=$?
if [ $RESULT_JEKYLL -ne 0 ]; then
 # Exit if build failed
 echo "\nDeployment failed: Jekyll build failed."
 exit 1
fi

echo "\nJekyll build successful."

# Cleans folder permissions
echo "Cleaning file & folder permissions in ${JEKYLL_DEST}..."
sudo chown -R root:remote $JEKYLL_DEST
sudo chmod -R 775 $JEKYLL_DEST

# Test if chown/chmod was succesfull
RESULT_CHMOD=$?
if [ $RESULT_CHMOD -ne 0 ]; then
 # Exit if failed
 echo "\nFailed cleaning permissions in ${JEKYLL_DEST}."
 echo "You might want to manually chmod/chroot at this point."
 exit 0
fi

echo "\nDone."
exit
