#!/bin/bash
#
# Script to perform a Jekyll deploy for moonlightradio.ddns.net
#

# Check if script is run as root.
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root."
  exit 1
fi

JEKYLL_DEST=/var/www/moonlightradio.ddns.net/public_html
WWW_ROOT=/var/www

echo -e "Building Jekyll site to ${JEKYLL_DEST}..."
bundle exec jekyll build -d $JEKYLL_DEST

# Test if jekyll build was succesfull
RESULT_JEKYLL=$?
if [ $RESULT_JEKYLL -ne 0 ]; then
  # Exit if build failed
  echo -e "\nDeployment failed: Jekyll build failed."
  exit 1
fi

echo -e "\nJekyll build successful."

# Cleans folder permissions
echo -e "Cleaning file & folder permissions in ${WWW_ROOT}...\n"
chown -R www-data:www-data $JEKYLL_DEST
chmod -R 755 $WWW_ROOT

# Test if chown/chmod was succesfull
RESULT_CHMOD=$?
if [ $RESULT_CHMOD -ne 0 ]; then
  # Exit if failed
  echo -e "\nFailed cleaning permissions in ${WWW_ROOT}"
  echo -e "You might want to manually chmod/chroot at this point."
  exit 0
fi

echo -e "Done."
exit
